### ISSUE TITLE
Inverted Colors

### ISSUE THREAD

**Issue by rlewkowicz** [SerpentAI/D3DShot#10]
I can't tell if this is open cv or this library, but one of the channels is messed up

![image](https://user-images.githubusercontent.com/17415445/65823508-ad429500-e225-11e9-9db3-2876f7287288.png)

vs what it's supposed to look like:

![image](https://user-images.githubusercontent.com/17415445/65823523-db27d980-e225-11e9-9aa0-5121ef6682a1.png)

I didn't see this issue with other libraries, but I might still be doing something wrong

**Comment by rlewkowicz** [comment]
OpenCV uses BGR as its default. 

`frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)`

**Comment by Arcitec** [comment]
D3DShot captures RGB images.

OpenCV's functions expect BGR images.

So, as you discovered, the solution is to convert the D3DShot image from `RGB -> BGR` via `cv2.cvtColor`.

PS: And btw, `cvtColor` is the _fastest_ way to do the color conversion. Numpy "magic math" is much slower, as proven here: https://answers.opencv.org/question/219040/fastest-way-to-convert-bgr-rgb-aka-do-not-use-numpy-magic-tricks/
