### ISSUE TITLE
The specified device interface or feature level is not supported on this system

### ISSUE THREAD

**Issue by hujiangchuan** [SerpentAI/D3DShot#17]
Hi
I encounter a problem in my W10 64bit laptop P51s, it's two video cards, nvidia and integrated intel.
I've setup nvdia as primary use and Dxdiag shows that Directx 12 is running normally.
Here is my code:
```
import time
import numpy as np
import d3dshot
p1=time.time()
d = d3dshot.create(capture_output="numpy")
img2=d.screenshot()
p2=time.time()
print ("it takes "+str(p2-p1)+ " seconds to capture in D3D.")

```

Traceback (most recent call last):
  File "C:/Users/jianghu/PycharmProjects/diaexplo/mess_d3d.py", line 14, in <module>
    d = d3dshot.create()
  File "C:\Python38\lib\site-packages\d3dshot\__init__.py", line 64, in create
    d3dshot = D3DShot(
  File "C:\Python38\lib\site-packages\d3dshot\d3dshot.py", line 24, in __init__
    self.detect_displays()
  File "C:\Python38\lib\site-packages\d3dshot\d3dshot.py", line 194, in detect_displays
    self.displays = Display.discover_displays()
  File "C:\Python38\lib\site-packages\d3dshot\display.py", line 109, in discover_displays
    display = cls(
  File "C:\Python38\lib\site-packages\d3dshot\display.py", line 40, in __init__
    self.dxgi_output_duplication = self._initialize_dxgi_output_duplication()
  File "C:\Python38\lib\site-packages\d3dshot\display.py", line 66, in _initialize_dxgi_output_duplication
    return d3dshot.dll.dxgi.initialize_dxgi_output_duplication(self.dxgi_output, self.d3d_device)
  File "C:\Python38\lib\site-packages\d3dshot\dll\dxgi.py", line 257, in initialize_dxgi_output_duplication
    dxgi_output.DuplicateOutput(d3d_device, ctypes.byref(dxgi_output_duplication))
_ctypes.COMError: (-2005270524, 'The specified device interface or feature level is not supported on this system.', (None, None, None, 0, None))

Process finished with exit code 1

Could you suggest what I should do to fix the issue?

**Comment by AramDonyaee** [comment]
I have this same problem as well, it would be great if you could help us to find a workaround. Thank you very much.

**Comment by gbrlfaria** [comment]
Does your computer (or laptop) have both integrated and dedicated GPUs? If so, then maybe it's related to the following issue: [Error generated when Desktop Duplication API-capable application is run against discrete GPU](https://support.microsoft.com/en-us/help/3019314/error-generated-when-desktop-duplication-api-capable-application-is-ru).

Basically, the Desktop Duplication API doesn't support being run against the dedicated GPU in this case. Thus, the function [DuplicateOutput](https://docs.microsoft.com/en-us/windows/win32/api/dxgi1_2/nf-dxgi1_2-idxgioutput1-duplicateoutput) fails and returns the error DXGI_ERROR_UNSUPPORTED (as we can see in the log you posted).

This was exactly my case and all I had to do was to force the python application to use the integrated GPU.

I'd suggest @nbrochu to document this since it's a quite shady issue and makes d3dshot unusable!

**Comment by nbrochu** [comment]
@gabriel-dev Thanks for making me aware of the use case of using it on laptops with hybrid GPUs (where I assume rendering gets switched from one to the other for power management purposes). I personally couldn't have anticipated this problem as I don't have a Windows laptop but it's very clear from what you linked that it runs into an issue on hybrid GPU systems.

To clarify for anyone else reading, it only causes an issue on laptops. I have multiple displays attached on my desktop, some on my discrete GPU, others on my integrated graphics and D3DShot works fine capturing any of them.

I'm really curious about the output of `d.displays` on laptop like these. If someone could help me out with that one that would be great.

I'd love to add a note to the documentation but I need to know what I'm dealing with first. Is the issue resolved by doing something in D3DShot (e.g. Picking a display set on the integrated graphics) or do you have do something outside to force Python to use that display adapter?

Also, not sure that this is necessarily the issue @hujiangchuan encountered but it could be. DXGI_ERROR_UNSUPPORTED can be raised in a lot of other cases like Windows<->Python bitness mismatch for example.

**Comment by nbrochu** [comment]
Someone getting this error in the dual-gpu laptop scenario reached out to me and we managed to get D3DShot fully working. There is no code fix required. As mentioned by @gabriel-dev, you need to make sure your python.exe and related processes you use (ipython, jupyter etc.) are set to be rendered exclusively on the integrated GPU. I will write a little guide for the wiki tomorrow and link to it from the readme in a warning to laptop users.

**Comment by nbrochu** [comment]
Added the [wiki article](https://github.com/SerpentAI/D3DShot/wiki/Installation-Note:-Laptops) and a mention in the README.
