### ISSUE TITLE
capture() fails with WinError[995]

### ISSUE THREAD

**Issue by zhichaoh** [SerpentAI/D3DShot#18]
I am trying to get high speed capture using capture->delay->stop. When calling creat(), I always got this exception:
```
Unhandled exception in event loop:
  File "C:\Python38\lib\asyncio\proactor_events.py", line 768, in _loop_self_reading
    f.result()  # may raise
  File "C:\Python38\lib\asyncio\windows_events.py", line 808, in _poll
    value = callback(transferred, key, ov)
  File "C:\Python38\lib\asyncio\windows_events.py", line 457, in finish_recv
    raise ConnectionResetError(*exc.args)

Exception [WinError 995] The I/O operation has been aborted because of either a thread exit or an application request
Press ENTER to continue...
```

This issue seems only to impact the ipython environment.

**Comment by nbrochu** [comment]
Apologies for the late reply. This appears to be an ipython bug with an issue that is still open: https://github.com/ipython/ipython/issues/12089

It's unrelated to D3DShot so I'm going to close the issue, but for the record, I also get it on Windows 10 once in a while with the latest ipython.
