### ISSUE TITLE
when I use cv2.imshow to see the screen shoot it appears scrambled

### ISSUE THREAD

**Issue by NatiBerko** [SerpentAI/D3DShot#20]
I'm trying to print the screenshot taken with D3DShot

d = d3dshot.create(capture_output="numpy")
while True:
    frame = d.screenshot(region=(140, 400, 540, 550))
    cv2.imshow("screenshot", frame)

frame comes scrambled.... can anyone explain?

thank you !

**Comment by WowSuchRicky** [comment]
Probably a dup of #19 . I'm having the same issue, also on a 3440x1440 monitor. I can reproduce that fact because the same code works great if I set the display to my secondary.

**Comment by nbrochu** [comment]
Yeah I'll mark it as a duplicate and flag the other one as a bug.
