### ISSUE TITLE
1,000,000+ fps in screen capture

### ISSUE THREAD

**Issue by Pro100rus32** [SerpentAI/D3DShot#39]
How can I start capturing on the same thread as my code?
Because getting the last frame is not an option, since I cannot find out when it changed.

example:
```
import d3dshot
from time import sleep, time
d = d3dshot.create(capture_output="numpy", frame_buffer_size=90)
d.capture(region=(653, 354, 713, 404))
sleep(1)
fps = 0
display_time = 1
start_time = 0
while True:
    test = d.get_latest_frame()
    fps+=1
    TIME = time() - start_time
    if (TIME) >= display_time :
        print("FPS: ", int(fps / (TIME)))
        start_time = time()
        fps = 0
```
Output:
```
FPS:  1562927
FPS:  1544829
FPS:  1702034
```
wtf? 1000000 fps?

**Comment by TheBlackPlague** [comment]
@Pro100rus32 I think you're forgetting to set `start_time` to `time.time()`.

**Comment by Pro100rus32** [comment]
> @Pro100rus32 I think you're forgetting to set `start_time` to `time.time()`.

No, everything is correct here. I found the problem. The capture is running on a different thread.
